framework:
    secret: '%env(APP_SECRET)%'
    annotations: false
    http_method_override: false
    handle_all_throwables: true
    php_errors:
        log: true
    router:
        default_uri: '%scheme%://%domain%/'
    assets:
        base_urls:
            - '%scheme%://%domain%/'
    http_client:
        max_host_connections: 10

when@test:
    framework:
        test: true
