twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        posthog_key: '%env(POSTHOG_KEY)%'
        posthog_api_host: '%env(POSTHOG_API_HOST)%'
        posthog_ui_host: '%env(POSTHOG_UI_HOST)%'