parameters:
    scheme: '%env(SCHEME)%'
    domain: '%env(DOMAIN)%'
    router.request_context.base_url: '%env(SCHEME)%://%env(BASE_URL)%'
    router.request_context.host: '%env(DOMAIN)%'
    router.request_context.scheme: '%env(SCHEME)%'

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    NorbertTech\Portfolio\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    NorbertTech\Portfolio\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    NorbertTech\Portfolio\StaticSourceProvider\:
        resource: '../src/StaticSourceProvider/'
        tags: ['static_content_generator.source_provider']

    NorbertTech\Portfolio\Blog\Posts:
